// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcqfqzhgludrzkfajljp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjcWZxemhnbHVkcnprZmFqbGpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MjQ1OTAsImV4cCI6MjA2OTAwMDU5MH0.N2F1BZq7ZJig-GSdr2Kv_WkHtWHI5bVS4JaKkc1u-Sk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});